name: Pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.105.0'
        extended: true

    - name: Build
      run: hugo --minify
    
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1.0.6
      with:
        # Artifact name
        name: 'mastodon-documentation'
        # Path of the directory containing the static assets.
        path: public/
        # Duration after which artifact will expire in days.
        retention-days: 1
    
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.3
      with:
        # Should this action only emit build telemetry instead of deploying the build artifact?
        emit_telemetry: false
